---
stages:
  - build
  - analyse
  - release
  - deploy

default:
  tags:
    - docker
  image: docker:latest

build:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

sonar-scanner:
  stage: analyse
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner -Dsonar.login=$SONAR_LOGIN -Dsonar.projectKey=op-shift-schedule -Dsonar.projectVersion=$CI_COMMIT_REF_NAME -Dsonar.sources=shifter,shifts,members
  only:
    - branches@accop/op-shift-schedule

release:
  stage: release
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - tags

deploy-to-test:
  stage: deploy
  image: registry.esss.lu.se/ics-docker/awxkit
  script:
    - >
      awx job_templates launch deploy-shifter-test
      --extra_vars "shifter_container_image_tag: $CI_COMMIT_REF_NAME"
      --monitor
  environment:
    name: test
    url: https://shifter-lab-01.cslab.esss.lu.se/
  rules:
    - if: $CI_PROJECT_PATH == "accop/op-shift-schedule"
      when: manual
