# Generated by Django 3.1.3 on 2021-02-20 11:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('date', 'slot', 'member', 'role', 'campaign', 'revision')},
        ),
    ]
