# Generated by Django 3.1.3 on 2021-02-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_auto_20210220_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='csv_upload_tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
