# Generated by Django 3.1.3 on 2021-02-23 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0003_shift_csv_upload_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shifts.campaign'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.member'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shifts.revision'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shifts.shiftrole'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shifts.slot'),
        ),
    ]
