# Generated by Django 3.1.3 on 2021-05-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_slot_color_in_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='op',
            field=models.BooleanField(default=False),
        ),
    ]
