# Generated by Django 3.1.3 on 2021-11-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_shiftermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=9)),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='shiftID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shifts.shiftid'),
        ),
    ]
