# Generated by Django 3.1.3 on 2022-03-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_auto_20211118_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='id_code',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
