# Generated by Django 3.2.12 on 2022-06-14 11:49

from django.db import migrations
from shifts.models import Slot, ShiftRole
from members.models import Role
import datetime


def create_basics(apps, schema_editor):
        print('Creating shifts slots')
        slot = Slot(name='Normal Working Hours', hour_start=datetime.time(8,0,0), hour_end=datetime.time(16,30,0), abbreviation='NWH', color_in_calendar='#47844D', op=True)
        slot.save()
        slot = Slot(name='Morning', hour_start=datetime.time(6,0,0), hour_end=datetime.time(14,00,0), abbreviation='AM', color_in_calendar='#47844D')
        slot.save()
        slot = Slot(name='Afternoon', hour_start=datetime.time(14, 0, 0), hour_end=datetime.time(22, 00, 00), abbreviation='PM', color_in_calendar='#4E779A')
        slot.save()
        slot = Slot(name='Night', hour_start=datetime.time(22, 0, 0), hour_end=datetime.time(6, 0, 0), abbreviation='NG', color_in_calendar='#222222')
        slot.save()

        print('Creating Member roles')
        roleLM = Role(name='LineManager', priority=50, abbreviation='LM')
        roleLM.save()
        roleLM = Role(name='ShiftLeader', priority=10, abbreviation='SL')
        roleLM.save()
        roleLM = Role(name='Operator', priority=30, abbreviation='OP')
        roleLM.save()
        roleLM = Role(name='SystemExpert', abbreviation='SE')
        roleLM.save()
        roleLM = Role(name='Study Leader', abbreviation='STL')
        roleLM.save()

        print('Creating Shifts roles')
        roleLM = ShiftRole(name='Office', abbreviation='OFF')
        roleLM.save()
        print('Done.')


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0010_slot_id_code'),
    ]

    operations = [
        migrations.RunPython(create_basics),
    ]
