# Generated by Django 3.2.16 on 2022-11-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0012_desiderata'),
    ]

    operations = [
        migrations.AddField(
            model_name='desiderata',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
