# Generated by Django 3.2.16 on 2023-03-20 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0012_auto_20230201_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftExchangePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shifts.shift')),
                ('shift_for_exchange', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='for_exchange', to='shifts.shift')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.DateTimeField()),
                ('approved', models.DateTimeField(blank=True, null=True)),
                ('applicable', models.BooleanField(default=False)),
                ('implemented', models.BooleanField(default=False)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('backupRevision', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='revision', to='shifts.revision')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('shifts', models.ManyToManyField(blank=True, to='shifts.ShiftExchangePair')),
            ],
        ),
    ]
