# Generated by Django 3.2.16 on 2022-12-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0013_desiderata_all_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Number'), ('link', 'URL')], default='phone', max_length=5)),
                ('contact', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact',
                'ordering': ['id'],
            },
        ),
    ]
