# Generated by Django 3.2.16 on 2023-10-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0013_auto_20230830_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftrole',
            name='color_in_calendar',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='shift',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Leave or early cancellation, IT IS NOT counted for the HR code.'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Last minute cancellation? IT IS counted for the HR code.'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='pre_comment',
            field=models.TextField(blank=True, help_text='Text to be displayed in shifters as shift constraint. [Shifters view ONLY]', null=True),
        ),
    ]
