# Generated by Django 3.1.3 on 2022-11-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0013_desiderata_all_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='merged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revision',
            name='name',
            field=models.CharField(default='Default', max_length=200),
        ),
        migrations.AddField(
            model_name='revision',
            name='ready_for_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slot',
            name='abbreviation',
            field=models.CharField(default='AM', max_length=10, unique=True),
        ),
    ]
