# Generated by Django 3.2.16 on 2022-12-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0014_auto_20221124_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='desiderata',
            name='type',
            field=models.CharField(choices=[('vac', 'Vacation'), ('conf', 'Conference'), ('other', 'Other')], default='vac', max_length=10),
        ),
    ]
