# Generated by Django 3.2.16 on 2022-12-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='fa_icon',
            field=models.CharField(default='fa-phone', max_length=50),
        ),
    ]
