# Generated by Django 3.2.16 on 2022-12-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0015_contact_fa_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
