# Generated by Django 3.2.16 on 2022-12-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0016_alter_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Number'), ('link', 'URL'), ('zoom', 'Zoom Link')], default='phone', max_length=5),
        ),
    ]
