# Generated by Django 3.2.16 on 2022-12-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0015_desiderata_type'),
        ('shifts', '0017_alter_contact_contact_type'),
    ]

    operations = [
    ]
