# Generated by Django 3.2.16 on 2023-01-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0018_merge_20221230_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='used_for_lookup',
            field=models.BooleanField(default=False),
        ),
    ]
