# Generated by Django 3.1.3 on 2021-12-17 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('license_plate', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('B', 'Booked'), ('R', 'Returned'), ('U', 'In Use')], default='B', max_length=1)),
                ('use_start', models.DateTimeField()),
                ('use_end', models.DateTimeField()),
                ('initial_comment', models.TextField(blank=True, default=None, max_length=2000, null=True)),
                ('booking_created', models.DateTimeField()),
                ('booking_finished', models.DateTimeField(blank=True, null=True)),
                ('after_comment', models.TextField(blank=True, default=None, max_length=2000, null=True)),
                ('booked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_member', to=settings.AUTH_USER_MODEL)),
                ('finished_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closing_member', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='using_member', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.vehicle')),
            ],
        ),
    ]
