# Generated by Django 3.1.3 on 2022-12-17 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrequest',
            name='slot_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 8, 11, 0, 732434)),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='slot_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 8, 11, 0, 732409)),
        ),
    ]
