# Generated by Django 3.2.16 on 2022-12-19 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_auto_20221217_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrequest',
            name='slot_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 8, 27, 4, 157287)),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='slot_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 8, 27, 4, 157267)),
        ),
    ]
