# Generated by Django 3.2.16 on 2023-01-02 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studies', '0002_auto_20221219_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrequest',
            name='collaborators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_using_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
