# Generated by Django 3.2.16 on 2022-12-19 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_auto_20221219_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrequest',
            name='slot_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 8, 34, 33, 119543)),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='slot_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 8, 34, 33, 119526)),
        ),
    ]
