# Generated by Django 3.2.16 on 2023-01-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_alter_studyrequest_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrequest',
            name='title',
            field=models.CharField(default='fuck', help_text='Title', max_length=200),
            preserve_default=False,
        ),
    ]
