# Generated by Django 3.2.16 on 2023-01-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_alter_studyrequest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrequest',
            name='duration',
            field=models.IntegerField(choices=[(1, '30 min'), (2, '60 min'), (3, '1.5 hour'), (4, '2.0 hours'), (5, '2.5 hours'), (6, '3 hours'), (7, 'more than 3 hours')], default=1, help_text='Study duration (30 min steps)'),
        ),
    ]
