# Generated by Django 3.2.16 on 2023-01-24 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_alter_studyrequest_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrequest',
            name='slot_end',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 16, 39, 11, 348552)),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='slot_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 16, 39, 11, 348530)),
        ),
    ]
