# Generated by Django 3.2.16 on 2023-01-24 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0008_auto_20230124_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyrequest',
            name='slot_end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='slot_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
