# Generated by Django 3.2.16 on 2023-01-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0009_auto_20230124_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrequest',
            name='booking_comment',
            field=models.TextField(blank=True, help_text='Comment regarding time slot', max_length=2000, null=True),
        ),
    ]
