# Generated by Django 3.2.16 on 2023-03-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0010_studyrequest_booking_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrequest',
            name='logbook_link',
            field=models.URLField(blank=True, help_text='Add an logbook link with study summary if possible', null=True),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='jira',
            field=models.URLField(blank=True, help_text='Add a JIRA link (or any other link connect to the study) if possible', null=True),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='state',
            field=models.CharField(choices=[('P', 'Planned'), ('R', 'Requested'), ('B', 'Booked'), ('C', 'Canceled'), ('D', 'Done')], default='P', max_length=1),
        ),
    ]
