# Generated by Django 3.1.3 on 2021-01-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='priority',
            field=models.IntegerField(blank=True, default=99),
        ),
    ]
