# Generated by Django 3.1.3 on 2021-02-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='abbreviation',
            field=models.CharField(default='OP', max_length=10),
        ),
    ]
