# Generated by Django 3.2.16 on 2022-11-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('view_desiderata', 'View Desiderata'),)},
        ),
    ]
