# Generated by Django 3.2.16 on 2022-12-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_contact_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
