# Generated by Django 3.2.16 on 2023-12-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='notification_shifts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='notification_studies',
            field=models.BooleanField(default=True),
        ),
    ]
